{   This include file is part of a CASE statement to resolve the subsystem
*   name given its ID.  This is part of routine SYS_ERROR_PRINT.
*
*   The include file for each of the subsystems declares a constant
*   xxx_SUBSYS_K, where XXX is the subsystem name.  Those declarations
*   *MUST* match the mappings here.
}
 -1: string_appends (subsys_v, 'sys');
 -2: string_appends (subsys_v, 'string');
 -3: string_appends (subsys_v, 'file');
 -4: string_appends (subsys_v, 'util');
 -5: string_appends (subsys_v, 'img');
 -6: string_appends (subsys_v, 'math');
 -7: string_appends (subsys_v, 'pginfo');
 -8: string_appends (subsys_v, 'syn');
 -9: string_appends (subsys_v, 'rend');
-10: string_appends (subsys_v, 'video');
-11: string_appends (subsys_v, 'sst');
-12: string_appends (subsys_v, 'epl8543');
-13: string_appends (subsys_v, 'tga');
-14: string_appends (subsys_v, 'centronics');
-15: string_appends (subsys_v, 'ray');
-16: string_appends (subsys_v, 'stuff');
-17: string_appends (subsys_v, 'dbuf');
-18: string_appends (subsys_v, 'dcont');
-19: string_appends (subsys_v, 'vect');
-20: string_appends (subsys_v, 'ci3000');
-21: string_appends (subsys_v, 'xl');
-22: string_appends (subsys_v, 'foto');
-23: string_appends (subsys_v, 'fifi');
-24: string_appends (subsys_v, 'res');
-25: string_appends (subsys_v, 'pub');
-26: string_appends (subsys_v, 'vox');
-27: string_appends (subsys_v, 'slide');
-28: string_appends (subsys_v, 'csrv');
-29: string_appends (subsys_v, 'dj850');
-30: string_appends (subsys_v, 'dr11w');
-31: string_appends (subsys_v, 'lc3000');
-32: string_appends (subsys_v, 'cirrus');
-33: string_appends (subsys_v, 'fsimio');
-34: string_appends (subsys_v, 'pdoc');
-35: string_appends (subsys_v, 'phot');
-36: string_appends (subsys_v, 'pwrio');
-37: string_appends (subsys_v, 'pwr');
-38: string_appends (subsys_v, 'chess');
-39: string_appends (subsys_v, 'chessv_prog');
-40: string_appends (subsys_v, 'motio');
-41: string_appends (subsys_v, 'cmd');
-42: string_appends (subsys_v, 'tric');
-43: string_appends (subsys_v, 'eball');
-44: string_appends (subsys_v, 'pic');
-45: string_appends (subsys_v, 'flop');
-46: string_appends (subsys_v, 'tsnet');
-47: string_appends (subsys_v, 'spball');
-48: string_appends (subsys_v, 'picprg');
-49: string_appends (subsys_v, 'ptap');
-50: string_appends (subsys_v, 'u1ex');
-51: string_appends (subsys_v, 'irlog');
-52: string_appends (subsys_v, 'rloc_prog');
-53: string_appends (subsys_v, 'prba');
-54: string_appends (subsys_v, 'ushos');
-55: string_appends (subsys_v, 'sentw');
-56: string_appends (subsys_v, 'usbcan');
-57: string_appends (subsys_v, 'ioext');
-58: string_appends (subsys_v, 'can');
-59: string_appends (subsys_v, 'touchtag');
-60: string_appends (subsys_v, 'ebox');
-61: string_appends (subsys_v, 'emcan');
-62: string_appends (subsys_v, 'escr');
-63: string_appends (subsys_v, 'email');
-64: string_appends (subsys_v, 'utest');
-65: string_appends (subsys_v, 'j1test');
-66: string_appends (subsys_v, 'jcan');
-67: string_appends (subsys_v, 'jowags');
